name: CI/CD
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '04 23 * * *'
jobs:
  Check-Workarounds:
    runs-on: ubuntu-latest
    concurrency:
      group: cicd-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: "Set environmental variables"
        run: |
          echo "INSTALLER_PATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Install tools
        run: |
          sudo apt -y update
          sudo apt install -y gcc-multilib
      - name: Run the installation script
        run: |
          cd $INSTALLER_PATH
          ./galacticusInstall.sh --galacticusPrefix=$INSTALLER_PATH/install --toolPrefix=$INSTALLER_PATH/install --asRoot=no --cores=2 --installLevel=minimal --setBash=yes --setCShell=no --ignoreFailures=no --packageManager=no --catLogOnError=yes
