name: CI/CD
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '04 23 * * 1'
concurrency:
  group: cicd-${{ github.ref }}
  cancel-in-progress: true  
jobs:
  Install-NonRoot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: "Set environmental variables"
        run: |
          echo "INSTALLER_PATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Install tools
        run: |
          sudo apt -y update
          sudo apt install -y gcc-multilib
      - name: Run the installation script
        run: |
          cd $INSTALLER_PATH
          ./galacticusInstall.sh --galacticusPrefix=$INSTALLER_PATH/galacticus --toolPrefix=$INSTALLER_PATH/install --asRoot=no --cores=2 --installLevel=minimal --setBash=yes --setCShell=no --ignoreFailures=no --packageManager=no --catLogOnError=yes
  Install-MacOS:
    strategy:
      # Ensure all jobs are run, even if some fail.
      fail-fast: false
      matrix:
        version: [ macos-12, macos-13, macos-14 ]
    runs-on: ${{ matrix.version }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: "Set environmental variables"
        run: |
          echo "INSTALLER_PATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Run the installation script
        run: |
          cd $INSTALLER_PATH
          ./galacticusInstallMacOS.sh
